import numpy as np

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum


class PowerSourceEnum(Enum):
	ConstantCurrent = "ConstantCurrent"
	ConstantVoltage = "ConstantVoltage"


class PowerSource(ABC):
	"""Abstract class for a general power sorurce"""

	@abstractmethod
	def current(self, resistance: float) -> float:
		"""Return the current generated by the power sorurce"""


class ConstantCurrent(PowerSource):
	"""Class for generating a constant current"""

	def __init__(self, current: float):
		"""
		I: float 	# The constant current supplied by the power source. Measured in Ampere
		"""
		self.I = current


	def current(self, resistance: float) -> float:
		return self.I


class ConstantVoltage(PowerSource):
	"""Class for generating a current from a constant voltage"""

	def __init__(self, voltage: float):
		"""
		voltage: float 	# The constant voltage over the power source. Measured in Volt
		"""
		self.voltage = voltage

	def current(self, resistance: float) -> float:
		return self.voltage / resistance
